# Generated by Django 3.2 on 2021-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('descricption', models.CharField(max_length=1000)),
                ('images', models.ImageField(default='', upload_to='images')),
                ('discounts', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('category', models.CharField(max_length=300)),
                ('offers', models.ManyToManyField(to='API.Offer')),
            ],
        ),
    ]
