# Generated by Django 3.2 on 2021-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_products_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='offer',
            name='detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='poster',
            field=models.ImageField(default='', upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
