# Generated by Django 3.2 on 2021-07-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210729_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='', upload_to='images')),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ManyToManyField(to='API.Images'),
        ),
    ]
