# Generated by Django 3.2 on 2021-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_images_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='images',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
