# Generated by Django 3.2 on 2021-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_deals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='products',
        ),
        migrations.AddField(
            model_name='products',
            name='deals',
            field=models.ManyToManyField(to='API.Deals'),
        ),
    ]
