# Generated by Django 3.2 on 2021-07-29 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0009_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=300)),
                ('fname', models.CharField(max_length=30)),
                ('mob_no', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('address_main', models.CharField(max_length=300)),
                ('address_local', models.CharField(max_length=300)),
                ('landmark', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Your order will be diliverd within the week', max_length=300)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.products')),
            ],
        ),
        migrations.CreateModel(
            name='Auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('Address', models.ManyToManyField(to='API.Address')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('orders', models.ManyToManyField(to='API.Orders')),
            ],
        ),
    ]
