# Generated by Django 3.2 on 2021-07-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_address_auth_user_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='API.products'),
        ),
    ]
