# Generated by Django 3.2 on 2021-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20210730_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='deals',
        ),
        migrations.AddField(
            model_name='deals',
            name='Products',
            field=models.ManyToManyField(to='API.Products'),
        ),
    ]
