# Generated by Django 3.2 on 2021-07-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_alter_deals_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='poster',
            field=models.ImageField(blank=True, default='', upload_to='posters'),
        ),
    ]
