# Generated by Django 3.2 on 2021-08-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0015_alter_deals_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('products', models.ManyToManyField(to='API.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.auth_user')),
            ],
        ),
    ]
